services:
  app1:
    depends_on:
      - db1
      - db2
    build: 
      context: ./method1
      dockerfile: ./Dockerfile
    image: flex-datasource1
    environment:
      - DB_PROTOCOL=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=host.docker.internal
      - DB_PORT=3307
      - DB_DATABASE=user
      - DB_CONNECTION_LIMIT=5
      - DB_POOL_TIMEOUT=2
    ports:
      - "3000:3000"

  app2:
    depends_on:
      - db1
      - db2
    build: 
      context: ./method2
      dockerfile: ./Dockerfile
    image: flex-datasource2
    environment:
      - DB_PROTOCOL=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=host.docker.internal
      - DB_PORT=3307
      - DB_DATABASE=user
      - DB_CONNECTION_LIMIT=5
      - DB_POOL_TIMEOUT=2
    ports:
      - "3001:3001"

  db1:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - 'db1:/var/lib/mysql'

  db2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - 'db2:/var/lib/mysql'
      
volumes:
  db1:
  db2: